# Generated by Django 6.0.5 on 2026-05-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='waste_type',
            field=models.CharField(default='General Waste', max_length=100),
        ),
    ]
