# Generated by Django 5.2.14 on 2026-05-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_complaint_waste_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='truck_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
