# Generated by Django 5.2.14 on 2026-05-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_truck_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned_team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
